### ISSUE TITLE
Several DIV's in accordion

### ISSUE THREAD

**Issue by lck-git** [zoltantothcom/vanilla-js-accordion#4]
Good work, thanks!

Is it possible to use the script with multiple DIV's under the button-Tag, see [demo](https://codepen.io/lck/pen/WNGNGGz).
How would the code have to be adapted. Is that even possible?

**Comment by zoltantothcom** [comment]
Since the script looks for the next `<div>` after the button you just need to wrap any number of `<div>`-s in a parent `<div>` and then you can style those children elements the way you want:

```html
 <button>Test multiple DIVs (Issue - Not possible at the moment)</button>
 <div>
    <div class="sub">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</div>
    <div class="sub">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</div>
 </div>
```

Hope this helps. Cheers!

**Comment by lck-git** [comment]
Thanks for your quick answer!
Yes, that helps. I had the same opportunity yesterday. But I didn't really want to implement it, because I had to change the existing code.

What is it about, briefly explained.
I want to convert an existing form with fieldset and legend Tags into an accordion with the help of your script. This works quite well so far, even with the above adjustment of the div's.
Now I have a problem with the fields with a textarea. These are changeable in height and width and that should stay that way. But now the problem is that the accordion content area doesn't change, because a certain height was created by script and this is fixed and not changeable.
[See demo](https://codepen.io/lck/pen/JjRjRVR).

Do you have an idea how to solve this? Could a change from height to minHeight in the script be the solution and overflow: auto?

**Comment by lck-git** [comment]
I could solve it with CSS :)

`.js-Accordion-content:not([style="height: 0px;"]) {
  height: auto !important;
}`

**Comment by zoltantothcom** [comment]
Thank you for posting your solution. I've added it to the package, so now it supports your use-case with changeable height containers.
